version: '3.1'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    env_file: .env
    networks:
      - backend
    volumes:
      - .:/backend

  db:
    image: postgres
    # restart: always  # Use in production
    env_file: .env
    networks:
      - backend
    ports: [5432:5432]  # Delete in production

networks:
  backend:
    name: menu-planner