INSERT INTO menu_planner.dishes( category, name, cost, observation )
VALUES
    ('Arroz branco', 'sem alho', 1, ''),
    ('Arroz integral', 'com seleta legumes sem alho', 1, ''),
    ('Feijão', 'Carioca', 1, ''),
    ('Carne bovina', 'Carne assada fatiada ao molho de manteiga com ervas finas', 3, '4/8 s/L'),
    ('Frango', 'Estrogonofe', 2, 'c/g c/L'),
    ('Peixe', 'Banda assada empanada no fubá', 2, ' com limão, sal e alho'),
    ('Proteína vegetal', 'Soja refogada com legumes', 1, ''),
    ('Massa', 'Macarrão s/G com açafrão, alho, salsa', 2, 'ESCOLA (500 g cru), gratinar ao molho Pomodoro'),
    ('Guarnição', 'Batata rústica', 1, ''),
    ('Guarnição', 'Brócolis al dente com cebola, alho e azeite', 1, 'Cortar cebola em meia lua'),
    ('Guarnição', 'Cenoura juliene refogada com ovos de codorna', 1, ''),
    ('Guarnição', 'Vagem ao molho pesto', 1, ''),
    ('Guarnição', 'Torta de abobrinha', 1, 'Fazer na forma retangular para cortar quadrados para dieta xuxu'),
    ('Guarnição', 'Banana da terra assada', 1, ''),
    ('Guarnição', 'Quiche ao alho poró', 1, 'c/g c/L'),
    ('Chá', 'Casca de laranja, canela e capim cidreira', 1, ''),
    ('Arroz branco', 'Normal', 1, ''),
    ('Arroz integral', 'Normal', 1, ''),
    ('Carne bovina', 'Cuiabaninho', 3, ''),
    ('Frango', 'Cubos de filé de frango marinado ao suco de laranja com sal, alho, salsa e orégano ', 2, 'cubos 2x2'),
    ('Peixe', 'Ventrecha assada empanada no fubá', 2, 'Passar no molho de tomate ao sugo e depois no fubá'),
    ('Proteína vegetal', 'Hamburguer de brócolis', 1, 'Vídeo para inspiração'),
    ('Massa', 'Bigoli com ervas final ao molho pomodoro', 2, 'Tomate 2x22, cebola 1x1, azeitona preta picadinha e folhas de manjericão rasgadas no final'),
    ('Guarnição', 'Batata doce assada', 1, 'Fatias médias, temperar com mel, raspas de limão, canela em pó (pouca) e salsinha'),
    ('Guarnição', 'Quiabo com carne moída e cebolinha', 1, 'Cortar cebola em meia lua'),
    ('Guarnição', 'Abobrinha verde', 1, 'Rodelas não muito finas, passar ovo e flocos de milho temperada com sal,alho e orégano'),
    ('Guarnição', 'Risoto de abóbora Cabotiã', 1, 'Ver o vídeo Bia - com alho poró'),
    ('Guarnição', 'Creme de milho verde', 1, ''),
    ('Chá', 'Camomila com abacaxi', 1, '')
;